spring:
  datasource:
    username: postgres
    password: pass
  artemis:
    user: artemis
    password: artemis
aws:
  s3:
    accessKey: ievgIQw0QLGQhbTPqvE4
    secretKey: RQFv6I5R2UusK2tlpygHeFwjcjvyvcs3g6qkcA4J