spring:
  application:
    name: File-Management Service
  datasource:
    url: jdbc:postgresql://localhost:5432/file_management
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8900/realms/yt-clone
  artemis:
    broker-url: tcp://localhost:61616
    transcodingQueue: jms/transcoderQueue
    managementQueue: jms/managementQueue
aws:
  s3:
    url: http://localhost:9000
    region: ap-south-1
    buckets:
      raw-videos: raw-videos
      transcoded-videos: transcoded-videos
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-components: always